/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPackage;

import ClassPackage.Cashier;
import ClassPackage.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Thanuja
 */
public class CashierLoginForm extends javax.swing.JFrame {

    /**
     * Creates new form ManagerLoginForm
     */
    public CashierLoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CashierUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CashierPassword = new javax.swing.JPasswordField();
        cashierLoginBtn = new javax.swing.JButton();
        backToMMBtn = new javax.swing.JButton();
        showPasswordCB = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cashier Login Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));
        jPanel1.add(CashierUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 200, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));
        jPanel1.add(CashierPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 200, 30));

        cashierLoginBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cashierLoginBtn.setText("Login");
        cashierLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierLoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cashierLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 80, -1));

        backToMMBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backToMMBtn.setText("Back To Main Menu");
        backToMMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMMBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backToMMBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, -1, -1));

        showPasswordCB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showPasswordCB.setForeground(new java.awt.Color(255, 255, 255));
        showPasswordCB.setText("Show Password");
        showPasswordCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCBActionPerformed(evt);
            }
        });
        jPanel1.add(showPasswordCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 130, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ManagerMenu.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 1290, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToMMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMMBtnActionPerformed
        this.toBack();
        UserMainMenu mm = new UserMainMenu();
        mm.setVisible(true);
        mm.toFront();
        dispose();
    }//GEN-LAST:event_backToMMBtnActionPerformed

    private void cashierLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierLoginBtnActionPerformed
        boolean isValid = false;
        if (CashierUsername.getText().isEmpty() || CashierPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Feilds cannot be empty", "Cashier Login", JOptionPane.WARNING_MESSAGE);
        } else {
            String userName = CashierUsername.getText();
            String password = CashierPassword.getText();

            User chr = new Cashier();
            
            if (chr.validateUser(userName, password)) {
                JOptionPane.showMessageDialog(null, "Logged In!");
                this.toBack();
                CashierOptions co = new CashierOptions();
                co.setVisible(true);
                co.toFront();
                dispose();
                

            } else {
                JOptionPane.showMessageDialog(rootPane, "Please enter valid Username and Password!", "Login Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_cashierLoginBtnActionPerformed

    private void showPasswordCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCBActionPerformed
        if (showPasswordCB.isSelected()) {
            CashierPassword.setEchoChar((char) 0);
        } else {
            CashierPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierLoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CashierPassword;
    private javax.swing.JTextField CashierUsername;
    private javax.swing.JButton backToMMBtn;
    private javax.swing.JButton cashierLoginBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox showPasswordCB;
    // End of variables declaration//GEN-END:variables
}
